// Code generated by MockGen. DO NOT EDIT.
// Source: capability.go
//
// Generated by this command:
//
//	mockgen -source=capability.go -destination=mock_capability_test.go -package=plugin
//

// Package plugin is a generated GoMock package.
package plugin

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCapability is a mock of Capability interface.
type MockCapability struct {
	ctrl     *gomock.Controller
	recorder *MockCapabilityMockRecorder
	isgomock struct{}
}

// MockCapabilityMockRecorder is the mock recorder for MockCapability.
type MockCapabilityMockRecorder struct {
	mock *MockCapability
}

// NewMockCapability creates a new mock instance.
func NewMockCapability(ctrl *gomock.Controller) *MockCapability {
	mock := &MockCapability{ctrl: ctrl}
	mock.recorder = &MockCapabilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapability) EXPECT() *MockCapabilityMockRecorder {
	return m.recorder
}

// Invoke mocks base method.
func (m *MockCapability) Invoke(ctx context.Context, input []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", ctx, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockCapabilityMockRecorder) Invoke(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockCapability)(nil).Invoke), ctx, input)
}

// Name mocks base method.
func (m *MockCapability) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCapabilityMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCapability)(nil).Name))
}

// MockHTTPDoer is a mock of HTTPDoer interface.
type MockHTTPDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPDoerMockRecorder
	isgomock struct{}
}

// MockHTTPDoerMockRecorder is the mock recorder for MockHTTPDoer.
type MockHTTPDoerMockRecorder struct {
	mock *MockHTTPDoer
}

// NewMockHTTPDoer creates a new mock instance.
func NewMockHTTPDoer(ctrl *gomock.Controller) *MockHTTPDoer {
	mock := &MockHTTPDoer{ctrl: ctrl}
	mock.recorder = &MockHTTPDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPDoer) EXPECT() *MockHTTPDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHTTPDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHTTPDoerMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHTTPDoer)(nil).Do), req)
}
