// Code generated by MockGen. DO NOT EDIT.
// Source: template.go
//
// Generated by this command:
//
//	mockgen -source=template.go -destination=mock_template_test.go -package=manifest
//

// Package manifest is a generated GoMock package.
package manifest

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTemplateEngine is a mock of TemplateEngine interface.
type MockTemplateEngine struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateEngineMockRecorder
	isgomock struct{}
}

// MockTemplateEngineMockRecorder is the mock recorder for MockTemplateEngine.
type MockTemplateEngineMockRecorder struct {
	mock *MockTemplateEngine
}

// NewMockTemplateEngine creates a new mock instance.
func NewMockTemplateEngine(ctrl *gomock.Controller) *MockTemplateEngine {
	mock := &MockTemplateEngine{ctrl: ctrl}
	mock.recorder = &MockTemplateEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateEngine) EXPECT() *MockTemplateEngineMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockTemplateEngine) Render(source string, template []byte, context map[string]any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", source, template, context)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Render indicates an expected call of Render.
func (mr *MockTemplateEngineMockRecorder) Render(source, template, context any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockTemplateEngine)(nil).Render), source, template, context)
}
