package lockfile

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// TestInteropWithJavaScriptLockfile reads a fixture produced by the actual
// JavaScript CLI — generated by calling its own emptyLock/writeLock, not
// hand-written to look like its output — and asserts this package both
// understands it and rewrites it byte for byte.
//
// This is the test that makes the format a contract rather than an intention.
// An environment created by one CLI is torn down by whichever one the user
// happens to run, so a field this package silently dropped would come back as
// an orphaned Cloudflare resource nobody is tracking, long after the change
// that caused it.
func TestInteropWithJavaScriptLockfile(t *testing.T) {
	original, err := os.ReadFile(filepath.Join("testdata", "js-written.lock.json"))
	if err != nil {
		t.Fatalf("reading the JS-written fixture: %v", err)
	}

	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, dirName), 0o700); err != nil {
		t.Fatal(err)
	}
	// The suppression below is a false positive: the name is a compile-time
	// constant Path has already validated, and dir is t.TempDir(). gosec's
	// taint analyser can see neither fact.
	if err := os.WriteFile(mustPath(t, dir, "interop-env"), original, 0o600); err != nil { //nolint:gosec
		t.Fatal(err)
	}

	lock, err := Read(dir, "interop-env")
	if err != nil {
		t.Fatalf("could not read a lockfile the JavaScript CLI wrote: %v", err)
	}
	if lock.ElVersion != "0.5.0" || lock.AccountID != "acct-9" || lock.Subdomain != "sub-9" {
		t.Fatalf("scalar fields did not decode: %+v", lock)
	}
	if lock.Database == nil || lock.Database.Provider != "neon" {
		t.Fatalf("database did not decode: %+v", lock.Database)
	}

	// The provider's own payload must survive intact without this package
	// knowing its shape — that opacity is the point of json.RawMessage here.
	var payload struct {
		BranchID   string   `json:"branchId"`
		BranchName string   `json:"branchName"`
		Hyperdrive []string `json:"hyperdrive"`
	}
	if err := json.Unmarshal(lock.Database.Lock, &payload); err != nil {
		t.Fatalf("provider lock payload did not survive decoding: %v", err)
	}
	if payload.BranchID != "br-1" || payload.BranchName != "b" || len(payload.Hyperdrive) != 1 {
		t.Fatalf("provider payload lost data: %+v", payload)
	}

	svc, ok := lock.Services["api"]
	if !ok {
		t.Fatal("the api service did not decode")
	}
	if svc.WorkerName != "interop-env-api" || svc.WranglerVersion != "4.1.0" {
		t.Fatalf("service scalars did not decode: %+v", svc)
	}
	if len(svc.Resources.D1) != 1 || svc.Resources.D1[0].Name != "interop-env-api-db" {
		t.Fatalf("service resources did not decode: %+v", svc.Resources)
	}
	if len(svc.CompatibilityFlags) != 1 || svc.CompatibilityFlags[0] != "nodejs_compat" {
		t.Fatalf("compatibility flags did not decode: %+v", svc.CompatibilityFlags)
	}

	// Rewrite it and require the bytes back unchanged: indentation, key order,
	// trailing newline, empty lists as [] and absent database as null.
	out := t.TempDir()
	if err := Write(out, lock); err != nil {
		t.Fatalf("Write: %v", err)
	}
	rewritten, err := os.ReadFile(mustPath(t, out, "interop-env"))
	if err != nil {
		t.Fatal(err)
	}
	if string(rewritten) != string(original) {
		t.Fatalf("rewrite is not byte-identical to the JavaScript CLI's output.\n--- written by node ---\n%s\n--- rewritten by go ---\n%s", original, rewritten)
	}
}
